### ISSUE TITLE
LEVEL3 과제 리뷰

### ISSUE THREAD

**Issue by dewey-89** [tuto3355/springLv3_pair#1]
저는 패키지를 기능 기준으로 분류해왔었는데, 구현하신 코드를 보니 비즈니스 모델? 별로 패키지가 정리되어 있어 보기 편했습니다. 깔끔하고 기능별로 잘 구현된 것 같습니다.

너무 잘 정리 되어 있고, 기능들도 의도에 맞게 잘 구현 되어있는 것 같습니다.
시큐리티 붙이기 전까지 과제 의도에 맞게 구현하셔서 건드릴 부분이 없는 것 같습니다.
고생하셨습니다.

**Comment by Lazencas** [comment]
패키지가 보드, 댓글, 유저 이렇게 잘 나누어져 있어어 보기가 편안했습니다.
기능이 잘 구현되도록 로직들이 잘 작성되어 있는거 같습니다. 특히 주석이 부분 부분 잘 들어가 있어서 좋았습니다.

저는 토큰이 필요한 기능들에서 토큰의 파라미터를 @CookieValue로 받았는데, HttpServletRequest req로 받으신 부분이 저랑 달라서 저렇게 할 수도 있구나! 했습니다.
